### ISSUE TITLE
EC2 to/from Lightsail using FQDN and PRIVATE IPs

### ISSUE THREAD

**Issue by dshirsh** [awsdocs/amazon-lightsail-developer-guide#48]
Using Route53 to handle split-horizon DNS for EC2 and Lightsail (LS) instances. Would like to use LS instance private IP to facilitate data transfers to/from EC2 without data transfer costs. I can ping between the LS and EC2 just fine with the privates. FQDN resolves OK from EC2 to LS but does not work in the opposite direction. I guess the issue is how do you get LS to participate in a private domain zone in Route53. Lightsail DNS does not seem to support private domain zones. Couldn't find any articles on this type of situation.

**Comment by rlatino** [comment]
Lightsail DNS zones do not support private domain zones. As you stated, the Route 53 hosted zones do support private domain zones.

As a background: All of your Lightsail resources are within a Lightsail VPC, which you can peer to your default AWS VPC.

I'm not sure if peering the Lightsail VPC with your AWS VPC will allow you to then use your Lightsail resources in a private domain zone in Route 53. I imagine you would need to add the default AWS VPC (that the Lightsail VPC is peered to) to your private domain zone, and then make an attempt to communicate with your Lightsail resources. If that doesn't work, then I don't believe Lightsail resources can participate in private domain zones in Route 53. If in doubt, I recommend opening a support ticket with AWS so that they can investigate this a bit more. My ability to investigate issues over GitHub is very limited.
