### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by vaoneiler** [awsdocs/amazon-lightsail-developer-guide#61]
After creating Distribution with my instance as the origin. I am getting ERR_TOO_MANY_REDIRECTS.
I went through the docs and configured everything as required. 
has anyone seen this before.
- Certs are valid and I have updated wp-config.php file per documentation
Site: [redacted]  and [redacted] 
curl: (47) Maximum (50) redirects followed

---

**Comment by rlatino** [comment]
Hi @vaoneiler ,

I have redacted the domains from your post. Unfortunately, there's very little assistance we can provide over Git without making your information public, and without being able to look into the configuration of your instance. I recommend opening a ticket with AWS Support so that they can investigate the issue with you. https://docs.aws.amazon.com/awssupport/latest/user/getting-started.html
